#DataSource Configuration

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: Manoj1
    
    
#JPA Configuration

  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle10gDialect
  
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
  
  
  
    properties:
     hibernate:
      dialect: org.hibernate.dialect.OracleDialect
      format_sql: true
            
server:
    port: 10002 
    
security:
  jwt:
    secret: secret